name: Deploy File to cPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # - name: Check FTPS support
      #   run: |
      #     curl --ssl-reqd --output /dev/null --silent --head --fail ftp://$FTP_SERVER

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: 🔨 Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm cache clean --force
          npm install
          git reset --hard

      - name: 🔨 Cache Busting
        run: |
          # Example command to add version number or hash to file names
          # This assumes you have a script to handle cache busting
          npm run cache-bust

      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          
